pipeline {

    agent any 

    environment {
        APP_NAME = "wedding-invitation"
        SERVER_IP = "13.127.249.241"
    }

    stages {

         stage('checkout'){
              steps{
                  checkout scm
              }
         }

         stage('maven build and Deploy'){
            steps {
                sh '''
                     ssh ubuntu@${SERVER_IP} "
                     sudo rm -rf wedding-webapp
                     git clone https://github.com/venkat01012004/wedding-webapp.git
                     cd wedding-webapp/${APP_NAME}
                     mvn clean package
                     sudo cp target/${APP_NAME}.war /opt/tomcat/webapps/
                     "
                   '''
            }
         }

    }
}
